global:
  scrape_interval: 10s

  external_labels:
    monitor: 'ocgrpc-java' 

scrape_configs:
  - job_name: 'ocgrpc-java'

    scrape_interval: 10s

    static_configs:
      - targets: ['localhost:9821']
